sudo: required
dist: trusty
os:
- linux
- osx
language: generic
cache:
  directories:
  - "$HOME/.stack"
addons:
  apt:
    packages:
    - libgmp-dev
    - ruby
    - ruby-dev
    - rubygems
    - gcc
    - make
before_install:
- export PATH=$HOME/.local/bin:$PATH
- ./.travis-setup.sh
install:
- stack --no-terminal --install-ghc test --only-dependencies
script:
- stack --copy-bins --no-terminal build
- stack exec hprotoc -- -I lib/proto -I test/proto -d test -p Gen Prim.proto Arrays.proto SolTypes.proto Structs.proto Simple.proto solidity.proto
- stack test
- git clone git@github.com:CBAInnovationLab/packages.git
- ./packages/solpb/build.sh
deploy:
  provider: s3
  access_key_id: AKIAIRBCAOVO5336FAWQ
  region: ap-southeast-2
  bucket: protobuf-solidity
  skip_cleanup: true
  local_dir: build
  acl: public_read
  secret_access_key:
    secure: mf48M6jpRyt9uUEySc9X+dkKQkIcyzOYhM+Fu9C65MfKHRJ5nfGEalJohf3QrwE7eDoWgJ4+hDWE3SI61VdS4Pny8afkdvLLyzBGHqnQCOkWDjRdcVzQtyc3Xq3VmA3gahjUB4i1B+Tr6dy70T/3gXieGKPxagkGXaMlogg5gj3U2UKwV9FVbrpg8HcRYg1A64Tpx4azb/x+mk//CbtyjfdAPGV+fzf88FEmyQDqg5xYORHcZyH6SR7qQt2uPCc0t7xqEVyTXtzlW+01eax/6PhDtt1ed5yyEl7GEAHBu49nA6x2le/+gMMm1LXP2fV4NBbVvd1SFFMLFHDjniXkMy20+cY5jnCXeqnmSELZoif8ve7KMe7m6hAizuT6G/SGHKlXs6ApnFmFGE/TgBdEJLDQJ1i1FiKBpHQaBiLv7khq4+F62at2LnWCH1/0j/4mwKx9T7rKfWcT2I4RgRLsrkKtArA+iSmohU6RdmKMZY1/ltaESK0vZB9qizS2phwMFglv9BGGHeUM3zGwhw143FnW+RA17pzNq/CL2rgWYPSwOJmr4TurJzouoTnSu0K6PjLTIGVcm2oKGlXY+8DtHdfPqNAXL1daITJ/KdiUmmewVSpabKsFZuoAutXFMAXnY8UfwqgZRk8UldRWpHO/+9PK1y/zrkkjffP7JZdwuXM=
