language: haskell
ghc: 7.8
before_script:
  - stack setup
script:
  - stack build
notifications:
  slack:
    secure: J+w1Vc/OxFhj5KrCvcssSfMNnIdfq9cQeXoY/S1fnbdGHoM1hOoJHSg44+DNgeD7I8Sv6hjGmulDPIhdegIVyvtXO5qTLLB5OTCzHGpq1tQU8XVaqyUr7vhwI56kK6vUujSDmFdk95rt1GJN2JipbayUXZ4YXnS6IDHCnCKyOpSGaSRHhlHghTJ4ymuEf1YY7WhcIzybdYhXy9ERdqofx0EQWADPSqiFlDj6oUsZxXikt5CLWd1d0hhURsJ03UdqQuPvu1Ta5qZ8pkROwIslPPxozS+jR3fBbVdMWpwEZ2/eXV3YTRhZAXwMRJtFzjV5K12LObBKIZhxFnUuHi7bJG9cgwcKuIS8p/9x5Nht174Dbj2MjuNUkkGeWcO99LgKnGlRgaUm3vkXKc/hia6lXKmJHcut5qZ+DaZOJjijtfsaewlm9oZ+4Xb7FlrjIrF2nvG8GELDl2LCSg+PoHRQ+j77og6YlPzrLSOH2o3Av/7Mk5Sn1MkvMxgOdXd59HS0Jsz+3opaBMUNUOXUcF1hx1/jy2yobRmp4iJhnLVydLqJrC0a5HcFGFtjNSnb1uhU/LKbGY6xmr2oeNnBpdanmqCr3N1Ht6HceQ9rI0bIrE4Yqu81dulXyybxMYQ7F1rmcxk40SuuIm1t+menNjCqvOQfQTIiUZfzZJ/TNR3uv/Y=
